name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Install depencencies
        run: | 
          make install
      - name: Lint
        run: | 
          make lint
      - name: Test
        run: | 
          make test
